import archiver from 'archiver';
import { Response } from 'express';
import { IVulnerability } from '../db/models/Scan.model.js';
import axios from 'axios';

export class DownloadService {
  private static readonly GITHUB_API_URL = 'https://api.github.com';

  /**
   * Download fixed files as ZIP
   */
  static async downloadFixedFilesZip(
    res: Response,
    repoFullName: string,
    defaultBranch: string,
    vulnerabilities: IVulnerability[],
    accessToken: string
  ): Promise<void> {
    try {
      // Set response headers for ZIP download
      res.setHeader('Content-Type', 'application/zip');
      res.setHeader('Content-Disposition', `attachment; filename="${repoFullName.replace('/', '-')}-security-fixes.zip"`);

      // Create ZIP archive
      const archive = archiver('zip', {
        zlib: { level: 9 } // Maximum compression
      });

      // Pipe archive to response
      archive.pipe(res);

      // Group vulnerabilities by file
      const vulnsByFile = new Map<string, IVulnerability[]>();
      for (const vuln of vulnerabilities) {
        if (!vuln.fixAvailable) continue;
        
        if (!vulnsByFile.has(vuln.file)) {
          vulnsByFile.set(vuln.file, []);
        }
        vulnsByFile.get(vuln.file)!.push(vuln);
      }

      // Process each file
      for (const [filePath, vulns] of vulnsByFile.entries()) {
        try {
          // Get current file content
          const fileResponse = await axios.get(
            `${this.GITHUB_API_URL}/repos/${repoFullName}/contents/${filePath}?ref=${defaultBranch}`,
            {
              headers: {
                Authorization: `Bearer ${accessToken}`,
                Accept: 'application/vnd.github.v3+json',
              },
            }
          );

          let content = Buffer.from(fileResponse.data.content, 'base64').toString('utf-8');

          // Apply fixes
          const sortedVulns = vulns.sort((a, b) => b.line - a.line);
          for (const vuln of sortedVulns) {
            content = this.applyFix(content, vuln);
          }

          // Add fixed file to archive
          archive.append(content, { name: filePath });
        } catch (error) {
          console.error(`Error processing file ${filePath}:`, error);
        }
      }

      // Add README with fix summary
      const readme = this.generateFixSummary(vulnerabilities, repoFullName);
      archive.append(readme, { name: 'SECURITY_FIXES_README.md' });

      // Finalize archive
      await archive.finalize();
    } catch (error: any) {
      console.error('Error creating ZIP:', error);
      throw new Error(`Failed to create ZIP file: ${error.message}`);
    }
  }

  /**
   * Apply a single fix to file content
   */
  private static applyFix(content: string, vuln: IVulnerability): string {
    const originalCode = vuln.originalCode.trim();
    const patchedCode = vuln.patchedCode.trim();
    return content.replace(originalCode, patchedCode);
  }

  /**
   * Generate fix summary README
   */
  private static generateFixSummary(vulnerabilities: IVulnerability[], repoFullName: string): string {
    const summary = {
      critical: vulnerabilities.filter(v => v.severity === 'critical' && v.fixAvailable).length,
      high: vulnerabilities.filter(v => v.severity === 'high' && v.fixAvailable).length,
      medium: vulnerabilities.filter(v => v.severity === 'medium' && v.fixAvailable).length,
      low: vulnerabilities.filter(v => v.severity === 'low' && v.fixAvailable).length,
    };

    let readme = `# Security Fixes for ${repoFullName}\n\n`;
    readme += `Generated by VulnixAI on ${new Date().toLocaleString()}\n\n`;
    
    readme += `## Summary\n\n`;
    readme += `This ZIP contains fixed versions of files with security vulnerabilities.\n\n`;
    readme += `- 🔴 Critical: ${summary.critical}\n`;
    readme += `- 🟠 High: ${summary.high}\n`;
    readme += `- 🟡 Medium: ${summary.medium}\n`;
    readme += `- 🟢 Low: ${summary.low}\n`;
    readme += `- **Total Fixed**: ${summary.critical + summary.high + summary.medium + summary.low}\n\n`;
    
    readme += `## Files Included\n\n`;
    
    const byFile = new Map<string, IVulnerability[]>();
    for (const vuln of vulnerabilities) {
      if (!vuln.fixAvailable) continue;
      if (!byFile.has(vuln.file)) {
        byFile.set(vuln.file, []);
      }
      byFile.get(vuln.file)!.push(vuln);
    }

    for (const [file, vulns] of byFile.entries()) {
      readme += `### ${file}\n\n`;
      for (const vuln of vulns) {
        readme += `- **${vuln.title}** (${vuln.severity})\n`;
        readme += `  - Line ${vuln.line}\n`;
        readme += `  - ${vuln.description}\n`;
        readme += `  - CWE: ${vuln.cweId}\n\n`;
      }
    }

    readme += `## How to Use\n\n`;
    readme += `1. Extract this ZIP file\n`;
    readme += `2. Review the fixed files\n`;
    readme += `3. Copy the fixed files to your repository\n`;
    readme += `4. Test thoroughly\n`;
    readme += `5. Commit and push\n\n`;
    
    readme += `## Important Notes\n\n`;
    readme += `⚠️ **Always review changes before deploying**\n`;
    readme += `⚠️ **Test all functionality after applying fixes**\n`;
    readme += `⚠️ **These fixes were generated by AI and may need adjustments**\n\n`;
    
    readme += `---\n`;
    readme += `Generated by VulnixAI - AI-Powered Security Scanner\n`;

    return readme;
  }
}
